# docker-compose.yml
#version: '3.8'
services:
  mppt_poller:
    build: .
    container_name: mppt_modbus_mqtt_poller
    restart: unless-stopped
    # 如果有抓不到設備的問題，可以開啟 host 網路模式
    # network_mode: "host" 
    volumes:
      # 將本機的 config.yaml 掛載進去，未來改設定只要改本機檔案並重啟即可
      - ./config.yaml:/app/config.yaml      
      # (可選) 在開發或除錯期，可以直接把整個 app 資料夾掛載進去，改 code 不用重 build
       - ./app:/app
    environment:
      - TZ=Asia/Taipei
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
